"""rename department

Revision ID: 18ecd2d180ee
Revises: b1bf566aa958
Create Date: 2025-01-16 21:44:45.802405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18ecd2d180ee'
down_revision = 'b1bf566aa958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
